add_newline = true
command_timeout = 200
follow_symlinks = true
format = """
[\\[](bold red)$username[@](bold red)$hostname[\\[](bold red)[$directory]($style)[\\]](bold red)
[$git_branch$git_status]($style)$character
"""

[username]
format = "[$user]($style)"
show_always = true

style_user = "bold red"
[hostname]
format = "[$hostname](bold red)[\\]](bold red)[$ssh_symbol](bold green)"
ssh_only = false
ssh_symbol = "\\[SSH\\]"
disabled = false

[character]
error_symbol = "[ ✗ # ](bold bg:bright-red fg:black)"
success_symbol = "[ + \\$ ](bold bg:green fg:black)"

## Default dir config
[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold red"
home_symbol = "~"
truncate_to_repo = false
truncation_length = 200
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style) "
style = "italic red"

[git_status]
format     = '[$all_status]($style)'
style      = "red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

