[settings]
ignored_config_paths = ["~/DOTFILES/quattro-dots"]

[env]
PI_CODING_AGENT_DIR="/home/$USER/.pi/agent"

[tools]
gh = "latest"
"github:can1357/oh-my-pi" = "latest"
"npm:command-code" = "latest"
node = "latest"
pi = "latest"
uv = "latest"

[settings.upgrade]
auto_prune = false

[tasks.pi]
raw_args = true
description = "Pi Vanilla | Launch"
run = 'PI_CODING_AGENT_DIR="/home/$USER/.pi/agent" pi'

[tasks.pi-ctf]
raw_args = true
description = "Pi CTF agent | Launch"
run = 'PI_CODING_AGENT_DIR="/home/$USER/.pi/agent_ctf" pi --append-system-prompt "${PI_CODING_ADENT_DIR}/../system-prompts/append_ctf_0.md"'

[tasks.pi-ctf-install]
raw_args = true
description = "Pi CTF agent | Install a plugin"
run = 'PI_CODING_AGENT_DIR="/home/$USER/.pi/agent_ctf" pi install'
