/* Palette generated by Omarchy from the active theme's colors.toml.
 * Rendered into ~/.local/state/omarchy/current/theme/ on every theme change.
 * Do not edit: rewritten each time.
 *
 * Variables only, no selectors. discord.css consumes these with fallbacks. */

:root {
  --qv-scheme: {{ mode }};

  /* Surfaces, recessed -> elevated.
   * s0..s2 come from the theme directly; s3/s4 are mixed toward the
   * foreground so they contrast in light and dark themes alike
   * (lighter_background is not reliably lighter than background). */
  --qv-s0: {{ darker_background }};
  --qv-s1: {{ dark_background }};
  --qv-s2: {{ background }};
  --qv-s3: {{ mix background foreground 6% }};
  --qv-s4: {{ mix background foreground 12% }};

  /* Text. The two dimmest steps are mixed toward the foreground rather than
   * taken from the theme: a theme's own dark_foreground lands around 2.9:1 on
   * the background, which is what makes muted text hard to read. 92% and 97%
   * are the smallest mixes that clear WCAG AA (4.5:1) on every surface of both
   * light and dark themes; any lower reintroduces unreadable muted text on the
   * lightest palettes. */
  --qv-tx:        {{ foreground }};
  --qv-tx-strong: {{ bright_foreground }};
  --qv-tx-dim:    {{ mix background foreground 92% }};
  --qv-tx-faint:  {{ mix background foreground 97% }};

  /* Accent. --qv-on-accent is the colour of text sitting on an accent fill,
   * such as a button or an unread badge. It is not simply the theme
   * background: whether the background is readable on the accent depends on
   * how light the accent itself is, and themes disagree. hooks/theme-set.d
   * resolves it per theme to whichever of the darkest surface or white gives
   * the better contrast, and substitutes the result into this variable. */
  --qv-accent:       {{ accent }};
  --qv-accent-hover: {{ mix accent bright_foreground 20% }};
  --qv-accent-dim:   {{ mix background accent 35% }};
  --qv-accent-faint: {{ mix background accent 12% }};
  --qv-on-accent:    QV_ON_ACCENT_PLACEHOLDER;

  /* Lines and interactive states */
  --qv-border:        {{ mix background foreground 20% }};
  --qv-border-strong: {{ mix background foreground 35% }};
  --qv-hover:         {{ mix background foreground 8% }};
  --qv-active:        {{ mix background foreground 16% }};

  /* Selection */
  --qv-sel:    {{ selection_background }};
  --qv-sel-fg: {{ selection_foreground }};
  --qv-muted:  {{ muted }};

  /* Hues */
  --qv-red:     {{ red }};
  --qv-green:   {{ green }};
  --qv-yellow:  {{ yellow }};
  --qv-orange:  {{ orange }};
  --qv-blue:    {{ blue }};
  --qv-cyan:    {{ cyan }};
  --qv-magenta: {{ magenta }};

  /* Channels, for the tokens Discord defines with alpha */
  --qv-bg-rgb:     {{ background_rgb }};
  --qv-fg-rgb:     {{ foreground_rgb }};
  --qv-accent-rgb: {{ accent_rgb }};
}