# Set $PATH such that it is not solely shell-local / terminal-local
# - Set in user-level systemd definitions (~/.config/environment.d/)
# - Hyprland + UWSM aware

PATH=${HOME}/.local/bin:${HOME}/.cargo/bin:${PATH}
